<a href="https://colab.research.google.com/github/Anubhav3084/Deep-Learning/blob/main/PyTorch_Tutorial/Basics_and_Gradient_Descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Basics and Gradient Descent**

In [ ]:
import torch

t1 = torch.tensor(4.)
t1

tensor(4.)

**4. is a shorthand for 4.0. It's used for creating floating point numbers**

In [ ]:
t1.dtype

torch.float32

**All the elements have same data type in a tensor**

In [ ]:
# vector
t2 = torch.tensor([4.,5,6])
t2

tensor([4., 5., 6.])

In [ ]:
# matrix
t3 = torch.tensor([[5.,6],
                   [1,2],
                   [7,3]])
t3

tensor([[5., 6.],
        [1., 2.],
        [7., 3.]])

In [ ]:
# 3 dimensional array
t4 = torch.tensor([[[11,12,13],
                    [1,2,3]],
                   [[1,5,7],
                    [2,3,5]]])
t4

tensor([[[11, 12, 13],
         [ 1,  2,  3]],

        [[ 1,  5,  7],
         [ 2,  3,  5]]])

In [ ]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [ ]:
print(t2)
t2.shape

tensor([4., 5., 6.])


torch.Size([3])

In [ ]:
print(t3)
t3.shape

tensor([[5., 6.],
        [1., 2.],
        [7., 3.]])


torch.Size([3, 2])

In [ ]:
print(t4)
t4.shape

tensor([[[11, 12, 13],
         [ 1,  2,  3]],

        [[ 1,  5,  7],
         [ 2,  3,  5]]])


torch.Size([2, 2, 3])

**It's not possible to create tensors with improper shape**

In [ ]:
t5 = torch.tensor([[5,6.,7],
                   [2,3]])
t5

ValueError: ignored

# **Tensor operations and gradients** 


*   We can combine tensors with the usual arithmetic operations





In [ ]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [ ]:
# arithmetic operations 
y = w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

 

*   We can compute derivative of y automaitcally w.r.t the tensors that have `requires_grad` set to `True`.
In our case it's w and b
*   To compute the derivatives, we can invoke the `.backward` method on our result `y`.





In [ ]:
# compute derivatives
y.backward()

The derivatives of `y` with respect to the input tensors are stored in the `.grad` propety of the respective tenosrs.

In [ ]:
# display gradients

print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


# **Tensor functions**


In [ ]:
# Create a tensor with a fixed value for every element
t6 = torch.full((3,2), 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [ ]:
t3

tensor([[5., 6.],
        [1., 2.],
        [7., 3.]])

In [ ]:
# concatenate two tensors with compatible shapes
t7 = torch.cat((t6,t3))
t7

tensor([[42., 42.],
        [42., 42.],
        [42., 42.],
        [ 5.,  6.],
        [ 1.,  2.],
        [ 7.,  3.]])

In [ ]:
# Compute the sine of each element
t8 = torch.sin(t7)
t8

tensor([[-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9589, -0.2794],
        [ 0.8415,  0.9093],
        [ 0.6570,  0.1411]])

In [ ]:
# Change the shape of a tensor
t9 = t8.reshape(3,2,2)
t9

tensor([[[-0.9165, -0.9165],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9589, -0.2794]],

        [[ 0.8415,  0.9093],
         [ 0.6570,  0.1411]]])

# **Interoperability with Numpy**

In [ ]:
import numpy as np

x = np.array([[1.,2],
              [3,4]])
x

array([[1., 2.],
       [3., 4.]])

We can convert numpy array to a PyTorch tensor using `torch.from_numpy`.




In [ ]:
# convert numpy array to tensor
y = torch.from_numpy(x)
y
x.dtype, y.dtype

(dtype('float64'), torch.float64)

We can convert PyTorch tensor to a  numpy array using `.numpy`.


In [ ]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])